// <auto-generated />
namespace OopRestaurant201807.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class setMenuItemCategorytorequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setMenuItemCategorytorequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201807171104579_set MenuItem.Category to required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
