// <auto-generated />
namespace OopRestaurant201807.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class setMenuItemCategory_IDdefaultvalue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setMenuItemCategory_IDdefaultvalue));
        
        string IMigrationMetadata.Id
        {
            get { return "201807171101098_set MenuItem.Category_ID default value"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
